import React from 'react';
import {StyleSheet, Dimensions} from 'react-native';
const {height, width} = Dimensions.get('window');

const styles = StyleSheet.create({
  maincontainer: {
    flex: 1,
    // opacity: 0,
  },
  container: {
    height: (height / 100) * 20,
    width: '100%',
    alignItems: 'center',
  },

  mainheader: {
    height: (height / 100) * 10,
    width: '95%',
    flexDirection: 'row',
    // marginHorizontal: '5%',
    alignItems: 'center',
    marginVertical: '18%',
    // backgroundColor: 'red',
    // justifyContent: 'space-between',
  },
  image: {
    height: '100%',
    width: '20%',
    backgroundColor: 'blue',
    borderRadius: 100,
  },
  headertext: {
    fontSize: 24,
    marginHorizontal: '2%',
    // fontWeight: 'bold',
    paddingBottom: 5,
    color: 'black',
    fontFamily: 'Roboto-Bold',
  },
  mid: {
    height: (height / 100) * 80,
    width: '100%',
    // borderRadius: 25,
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,

    overflow: 'hidden',
    alignItems: 'center',
    marginBottom: '20%',
  },
  pic: {
    height: '20%',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: '3%',
  },
  pic_1: {
    height: 80,
    width: 80,
    borderRadius: 100,
    backgroundColor: '#e3e1e1',
  },

  form: {
    height: '12%',
    width: '80%',
    marginHorizontal: '10%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  form_profile: {
    flexDirection: 'row',
    width: '50%',
    alignItems: 'center',
  },
  pic_text: {
    fontSize: 16,
    color: 'white',
    marginVertical: '2.5%',
    fontFamily: 'Roboto-Regular',
  },
  form_text: {
    fontSize: 18,
    color: 'white',
    // fontWeight: 'bold',
    fontFamily: 'Roboto-Medium',
  },
  form_text2: {
    fontSize: 18,
    color: 'white',
    fontFamily: 'Roboto-Regular',
  },
  picker: {
    height: '80%',
    width: '80%',
    backgroundColor: 'transparent',
    paddingHorizontal: '10%',
    color: 'white',
    // justifyContent: 'center',
  },
  form_input: {
    fontSize: 18,
    color: 'white',
    marginLeft: '1%',
    fontFamily: 'Roboto-Regular',
    // borderBottomWidth: 1,
    // borderBottomColor: 'white',
    alignItems: 'stretch',
    textDecorationLine: 'underline',
  },
  form_text1: {
    fontSize: 18,
    color: 'white',
    fontWeight: 'bold',
    marginLeft: '10%',
  },
  line: {
    height: '0.3%',
    backgroundColor: 'white',
    width: '80%',
    borderRadius: 100,
  },
  button_con: {
    flexDirection: 'row',
    width: '80%',
    height: '20%',
    justifyContent: 'space-between',
    marginTop: '10%',
  },
  button: {
    width: '40%',
    backgroundColor: 'white',
    height: '40%',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 100,
  },
  button_text: {
    color: 'black',
    fontSize: 22,
    fontWeight: 'bold',
  },
  centeredView: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  modalView: {
    height: '30%',
    width: '100%',
    backgroundColor: 'white',
    // padding: 35,
    justifyContent: 'space-between',
    paddingBottom: '10%',
    alignItems: 'center',
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
  },

  button_modal: {
    marginBottom: 5,
    height: '25%',
    backgroundColor: '#2453ed',
    width: '55%',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    flexDirection: 'row',
    marginVertical: '5%',
    borderRadius: 25,
  },
  button_modal1: {
    marginBottom: 5,
    height: '25%',
    backgroundColor: '#2453ed',
    width: '55%',
    alignItems: 'center',
    // justifyContent: 'space-evenly',
    flexDirection: 'row',
    marginVertical: '5%',
    borderRadius: 25,
  },
  textStyle: {
    color: 'white',
    // fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 20,
    fontFamily: 'Roboto-Medium',
    // marginLeft: '5%',
    marginRight: '1%',
    marginBottom: '1%',
    marginLeft: '2%',
  },
  modalText: {
    marginBottom: 15,
    textAlign: 'center',
  },
});
export default styles;
